package com.akash.auditapi.exception;

public enum ApiErrorCode {
    INVALID_TABLE_NAME,
    INVALID_PAGE_NUMBER,
    INVALID_PAGE_SIZE,
    AUDIT_TABLE_NOT_ACCEPTED,
    TABLE_NOT_ALLOWED,
    TABLE_PAIR_NOT_FOUND,
    MISSING_REQUIRED_COLUMN,
    HOLIDAY_NOT_FOUND,
    VALIDATION_FAILED,
    INVALID_REQUEST,
    DATABASE_ERROR,
    UNAUTHORIZED,
    INTERNAL_ERROR
}
